[project]
name = "pankegg"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[dependencies]
python = ">=3.8"
flask = "*"
pandas = "*"
numpy = "*"
scikit-learn = "*"
scipy = "*"
jinja2 = "*"
click = "*"
pip = "*"
importlib-metadata = "*"
