project:
  type: website
  
website:
  title: "PANKEGG"
  navbar:
    logo: figures/PANKEGG_logo_small.png
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/RVanDamme/PANKEGG

  sidebar:
    style: "floating"
    border: true
    search: true
    bread-crumbs: false
    contents:
      - section: "Home"
        contents:
          - index.qmd
      - section: "Getting Started"
        contents:
          - quickstart.qmd
          - input_files.qmd
      - section: "Installation"
        contents:
          - installation.qmd
          - installation_test.qmd
      - section: "The tools"
        contents:
          - tool_introduction.qmd
          - Pankegg_make_db.qmd
          - Pankegg_app.qmd
      - section: "Web Interface"
        contents:
          - web_interface.qmd
      - section: "Additional Information"
        contents:
          - CONTRIBUTING.md
          - authors.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    format-links: false

execute:
  freeze: auto