name: pankegg_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - flask
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - jinja2
  - click
  - pip
  - pip:
      - importlib-metadata
