on:
  workflow_dispatch:
  push:
    branches: separate_documentation

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true  # Ensure LaTeX is installed for PDF rendering

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs  # Specify the path to your Quarto project

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs  # Specify the path to your Quarto project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
