on:
  workflow_dispatch:
  push:
    branches: separate_documentation

name: Render PDF

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # Ensure LaTeX is installed for PDF rendering
          tinytex: true

      - name: Render Specific Quarto Document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: docs/PANKEGG_documentation.qmd

      - name: List files for debugging
        run: ls -la docs/-site/

      - name: Commit PDF
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/_site/PANKEGG_documentation.pdf
          git commit -m "Rendered PDF from PANKEGG_documentation.qmd"
          git push
